name: Pruebas unitarias
on:
  push:
    branches: [master]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Configuracion entorno
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependencias
        working-directory: ./blacklist_app
        run: poetry install --with dev

      - name: Correr pruebas con cobertura
        working-directory: ./blacklist_app
        run: poetry run pytest --cov=src --cov-report=term-missing --cov-fail-under=90
